-- 코드를 입력하세요
SELECT DATE_FORMAT(A.SALES_DATE, '%Y') AS YEAR
, DATE_FORMAT(A.SALES_DATE, '%m') AS MONTH
, B.GENDER
, COUNT(DISTINCT B.USER_ID) AS UESRS
FROM ONLINE_SALE A, USER_INFO B
WHERE A.USER_ID = B.USER_ID AND B.GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3